# Task 1: Data Cleaning & Preprocessing

# Objective

- Load the dataset using pandas
- Identify and handle missing values
- Remove duplicate rows
- Check and clean data types
- Save cleaned dataset for further analysis

# Problem Statement

The objective of this project is to clean and preprocess the raw house prediction dataset by handling missing values, removing duplicate rows, and improving overall data quality for further analysis.

In [1]:
# Import Pandas Library
import pandas as pd

In [2]:
# Load Dataset

df = pd.read_csv("house Prediction Data Set.csv")

# Display First 5 Rows

df.head()

,0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24
0,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
1,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
2,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
3,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
4,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7

In [3]:
# Display Dataset Shape

df.shape

(505, 14)

In [4]:
# Display Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   0.00632  505 non-null    float64
 1   18       505 non-null    float64
 2   2.31     505 non-null    float64
 3   0        505 non-null    int64
 4   0.538    505 non-null    float64
 5   6.575    505 non-null    float64
 6   65.2     505 non-null    float64
 7   4.09     505 non-null    float64
 8   1        505 non-null    int64
 9   296      505 non-null    int64
 10  15.3     505 non-null    float64
 11  396.9    505 non-null    float64
 12  4.98     505 non-null    float64
 13  24       505 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.4 KB

In [5]:
# Check Missing Values

df.isnull().sum()

0.00632    0
18         0
2.31       0
0          0
0.538      0
6.575      0
65.2       0
4.09       0
1          0
296        0
15.3       0
396.9      0
4.98       0
24         0
dtype: int64

In [6]:
# Remove Duplicate Rows

df = df.drop_duplicates()

print("Duplicate Rows Removed Successfully")

Duplicate Rows Removed Successfully

In [7]:
# Select Numerical Columns

num_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Fill Missing Numerical Values with Mean

for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

print("Numerical Missing Values Filled")

Numerical Missing Values Filled

In [8]:
# Select Categorical Columns

cat_cols = df.select_dtypes(include=['object']).columns

# Fill Missing Categorical Values with Mode

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Categorical Missing Values Filled")

Categorical Missing Values Filled

In [9]:
# Display Data Types

df.dtypes

0.00632    float64
18         float64
2.31       float64
0            int64
0.538      float64
6.575      float64
65.2       float64
4.09       float64
1            int64
296          int64
15.3       float64
396.9      float64
4.98       float64
24         float64
dtype: object

In [10]:
# Check Missing Values After Cleaning

df.isnull().sum()

0.00632    0
18         0
2.31       0
0          0
0.538      0
6.575      0
65.2       0
4.09       0
1          0
296        0
15.3       0
396.9      0
4.98       0
24         0
dtype: int64

In [11]:
# Display Cleaned Dataset

df.head()

,0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24
0,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
1,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
2,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
3,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
4,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7

In [12]:
# Save Cleaned Dataset

df.to_csv("Cleaned_House_Prediction.csv", index=False)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

In [13]:
# Completion Message

print("Data Cleaning and Preprocessing Completed Successfully")

Data Cleaning and Preprocessing Completed Successfully

# Conclusion

- Successfully loaded and cleaned the dataset using pandas.
- Identified and handled missing values.
- Removed duplicate rows from the dataset.
- Checked and verified data types.
- Saved the cleaned dataset successfully.
- Improved the overall quality of the dataset for further analysis and visualization.